[framework]
name = "reactor-netty"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Reactor Netty"
webserver = "None"
versus = "reactor-netty"
